############################
## CHANGE THESE
############################

baseURL: 'https://omarfaruk-k.github.io/omarfaruk-k.github.io'
title: omarfaruk-k.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


