############################
## Author
############################

author:
  name: Omar Faruk Khan
  image: author.png
  greeting: "CS Student | Backend Enthusiast"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/omarfaruk-k/
  # - link: https://github.com/omarfaruk-k/omarfaruk-k.github.io#readme
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/omarfaruk-k/
  - codeforces: https://codeforces.com/profile/omarfaruk
  - hackerrank: https://www.hackerrank.com/profile/omarfaruk_k
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:omarfaruk.k.cs@gmail.com
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:




<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-4QP733SWSX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-4QP733SWSX');
</script>


###############################
## OpenGraph & Twitter Cards
###############################

title: omarfaruk-k
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
